services:
  db:
    image: postgres:latest
    container_name: gearmind-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - default

#  telegram:
#    container_name: gearmind-bot
#    build:
#      context: .
#    depends_on:
#      db:
#        condition: service_healthy
#    env_file:
#      - .env-non-dev
#    networks:
#      - default

  api:
    container_name: gearmind-api
    build:
      context: .
    command: /app/start.sh
    volumes:
      - ./:/app/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env-non-dev
    ports:
      - 7777:8000
    networks:
      - default

  redis:
    image: redis:7
    container_name: gearmind-redis

  scheduler:
    container_name: gearmind-scheduler
    build: .
    command: python src/scheduler.py
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env-non-dev
    networks:
      - default


volumes:
  postgres_data:

networks:
  default:
