"""Add triggers and index

Revision ID: 11c52083918d
Revises: cf1a2b61d4ca
Create Date: 2025-03-24 11:56:20.433296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c52083918d'
down_revision: Union[str, None] = 'cf1a2b61d4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_cars_full', 'cars', ['full'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cars_full', table_name='cars')
    # ### end Alembic commands ###
