"""change relation from users to profile

Revision ID: 4eced21cf74b
Revises: 809b9cbcf82d
Create Date: 2025-04-10 18:43:11.159283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eced21cf74b'
down_revision: Union[str, None] = '809b9cbcf82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_game_profiles', 'level_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_tasks_user_id_fkey', 'users_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'users_tasks', 'users_game_profiles', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_tasks', type_='foreignkey')
    op.create_foreign_key('users_tasks_user_id_fkey', 'users_tasks', 'users', ['user_id'], ['id'])
    op.alter_column('users_game_profiles', 'level_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
