"""fix car model3

Revision ID: 5dacd21cbd7a
Revises: e73c35c127bf
Create Date: 2024-07-24 14:34:06.250351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dacd21cbd7a'
down_revision: Union[str, None] = 'e73c35c127bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_user_id_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['tg_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_user_id_fkey', 'cars', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
