"""add threshold to profile

Revision ID: 809b9cbcf82d
Revises: bd6024fc29ff
Create Date: 2025-04-10 18:33:40.796587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809b9cbcf82d'
down_revision: Union[str, None] = 'bd6024fc29ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_cars_brand', 'cars', ['brand_name'], unique=False)
    op.drop_index('idx_prompts_text', table_name='prompts')
    op.drop_index('idx_prompts_type_text', table_name='prompts')
    op.add_column('users_game_profiles', sa.Column('level_threshold', sa.Integer(), nullable=True))
    op.execute("UPDATE users_game_profiles set level_threshold = 100")
    op.alter_column('users_game_profiles', column_name='level_threshold', existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_game_profiles', 'level_threshold')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_prompts_type'), table_name='prompts')
    op.create_index('idx_prompts_type_text', 'prompts', ['type', 'text'], unique=False)
    op.create_index('idx_prompts_text', 'prompts', ['text'], unique=False)
    op.drop_index('idx_cars_brand', table_name='cars')
    # ### end Alembic commands ###
