"""Initial

Revision ID: 95e13239bfc9
Revises: 
Create Date: 2025-03-15 17:05:46.464574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import db
from db.models.prompts.schemas import TypesEnum
from db.models.users.schemas import UsersRolesTypeDecorator

# revision identifiers, used by Alembic.
revision: str = '95e13239bfc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('type', db.models.prompts.schemas.EnumsDecorator(length=17, enum_class=TypesEnum),
                              nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_prompts_type_text', 'prompts', ['type', 'text'], unique=False)
    op.create_index(op.f('idx_prompts_text'), 'prompts', ['text'], unique=False)
    op.create_index(op.f('idx_prompts_type'), 'prompts', ['type'], unique=False)

    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('role', UsersRolesTypeDecorator(length=13), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_users_tg_user_id', 'users', ['tg_user_id'], unique=True)

    op.create_table('cars',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('brand_name', sa.String(), nullable=False),
                    sa.Column('model_name', sa.String(), nullable=False),
                    sa.Column('gen_name', sa.String(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('requests',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('prompt_id', sa.UUID(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('response', sa.String(), nullable=False),
                    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### insert into Tables Base Info
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute(
        """
        WITH bot_data AS (
            SELECT uuid_generate_v4() AS id,
                   7433112188         AS tg_user_id,
                   'GearMindBot'      AS name,
                   'Бот'              AS role
        )
        INSERT INTO users(id, tg_user_id, name, role)
             SELECT id, tg_user_id, name, role
               FROM bot_data
        """
    )
    op.execute(
        """
        WITH prompt_data AS (
            SELECT uuid_generate_v4() AS id,
                   'Запчасти' AS type,
                   'Ты — профессиональный автомобильный механик. Строго соблюдай правила:
                    Проанализируй рынок в соответствии с автомобилем <carinfo> и дай пользователю актуальную информацию, которая ему поможет.

                    ### Жёсткие требования:
                    1. **Только HTML-теги**:
                       - Для жирного текста: <b>текст</b>
                       - Запрещено: **текст**, __текст__, любые Markdown-символы.

                    2. **Формат ответа**:
                    Хорошо, <username>!

                    📌 <b>Диагноз:</b> [Проблема + причина] 

                    🎯 <b>Варианты:</b>
                    1. <b>Оригинал</b> Название: Характеристика. Цена: ~XXXX рублей
                    2. <b>Аналог</b> Название: Характеристика. Цена: ~XXXX рублей

                    💡 <b>Совет:</b> [Обоснование БЕЗ технических терминов]

                    3. **Запрещено**:
                       - Символы * или ** для выделения
                       - Ссылки, артикулы, маркетплейсы
                       - Любые теги кроме <b>

                    ### Пример КОРРЕКТНОГО ответа:
                    Хорошо, <username>!

                    📌 <b>Диагноз:</b> Стук в подвеске (износ шаровой опоры)

                    🎯 <b>Варианты:</b>
                    1. <b>TRW Original</b>: Ресурс 80 000 км. Цена: ~9990 рублей
                    2. <b>CTR Аналог</b>: Гарантия 2 года. Цена: ~5499 рублей

                    💡 <b>Совет:</b> CTR — оптимальное соотношение цены и гарантии.

                    ### Пример НЕКОРРЕКТНОГО ответа (запрещён!):
                    📌 **Диагноз:** Стук в подвеске...

                    🎯 **Варианты:**
                    1. **TRW Original** — ресурс 80к км. Цена: 9 990 руб.

                    💡 **Совет:** Выбирайте CTR из-за цены.' AS text
             UNION ALL
            SELECT uuid_generate_v4(),
                   'Жидкости для авто',
                   'Ты — эксперт по автохимии. Строго следуй правилам:
                    Проанализируй рынок в соответствии с автомобилем <carinfo> и дай пользователю актуальную информацию, которая ему поможет.

                    Хорошо, <username>!

                    📌 <b>Требования:</b> [Допуск, вязкость, регион] 

                    🎯 <b>Варианты:</b>
                    1. <b>Марка + Название</b>: [Характеристики]. Цена: ~XXXX рублей
                    2. <b>Марка + Название</b>: [Особенность]. Цена: ~XXXX рублей
                    3. <b>Марка + Название</b>: [Кратко]. Цена: ~XXXX рублей

                    💡 <b>Совет:</b> [Рекомендация + риски]

                    Правила:
                    1. Только тег <b> и цифры (никаких <u>, <i>, ссылок и markdown)
                    2. Цены в формате: ~4500 рублей
                    3. Не более 5 характеристик на пункт
                    4. Допускается предлагать до 5 позиций
                    5. Если нет данных — "нет актуальном информации"

                    Пример:
                    Хорошо, <username>!

                    📌 <b>Требования:</b> Синтетика 5W-30, допуск API SP

                    🎯 <b>Варианты:</b>
                    1. <b>Mobil Super 3000</b>: Полный синтез, защита -40°C. Цена: ~4299 рублей
                    2. <b>ZIC X7</b>: Всесезонное, совместимость с турбиной. Цена: ~3190 рублей

                    💡 <b>Совет:</b> Mobil — лучшая защита для холодного климата. Не используйте масла без API SP!'
             UNION ALL
            SELECT uuid_generate_v4(),
                   'Аксессуары',
                   'Ты — профессиональный помощник, а также эксперт в области автомобильных аксессуаров. Строго следуй правилам:

                    Проанализируй рынок в соответствии с автомобилем пользователя - <carinfo> и запросом. Используй формат ответа ниже:
                    Формат ответа:
                    Хорошо, <username>!

                    📌 [Опиши запрос в 5-7 слов]

                    🎯 <b>Варианты:</b>
                    1. <b>[Бренд]</b> [Тип]: [Аромат], [особенность]. Цена: ~[XXXX] рублей
                    2. <b>[Бренд]</b> [Тип]: [Краткое описание]. Цена: ~[XXXX] рублей

                    💡 <b>Совет:</b> [Рекомендация в 1-2 предложение]

                    Правила:
                    1. Запрещены: ссылки, markdown (например, **), теги кроме <b> 
                    2. Цены в формате: 1500 руб
                    3. Никаких HTML-атрибутов: type="disc" и т.п.
                    4. Максимум 5 вариантов
                    5. Если не уверен в данных — напиши "нет актуальной информации"

                    Пример корректного ответа:
                    Хорошо, <username>!
                    📌 <b>Проблема:</b> Нужен ароматизатор с лавандой для зеркала

                    🎯 <b>Варианты:</b>
                    1. <b>Eikosha</b> Premium: лаванда, меловой наполнитель. Цена: ~1800 рублей
                    2. <b>Areon</b> Classic: лаванда, 45 дней действия. Цена: ~600 рублей

                    💡 <b>Совет:</b> Areon — оптимален по сроку действия и цене'
        )

        INSERT INTO prompts(id, type, text)
             SELECT id, type, text
               FROM prompt_data
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('cars')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index('idx_users_tg_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_prompts_type'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_text'), table_name='prompts')
    op.drop_index('idx_prompts_type_text', table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
