"""add ondelete scores

Revision ID: 9e4aa87bf393
Revises: a76f90739c49
Create Date: 2025-04-02 14:56:16.866280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4aa87bf393'
down_revision: Union[str, None] = 'a76f90739c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scores_user_id_fkey', 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key('scores_user_id_fkey', 'scores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
