"""initial migrations

Revision ID: 9f4866936a60
Revises: 
Create Date: 2024-11-04 19:38:18.658446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4866936a60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('tg_user_id'),
    sa.UniqueConstraint('tg_username')
    )
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('maker', sa.String(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('toque', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['products_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('busbars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('maker', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('thorns', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['products_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('gen_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('maker', sa.String(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['products_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oils',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('maker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('liter', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('structure', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['products_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oils')
    op.drop_table('disks')
    op.drop_table('cars')
    op.drop_table('busbars')
    op.drop_table('batteries')
    op.drop_table('users')
    op.drop_table('products_types')
    # ### end Alembic commands ###
