"""add add roles

Revision ID: a2ce75f58c99
Revises: 9e4aa87bf393
Create Date: 2025-04-02 21:29:52.576741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.models.users.schemas import UsersRolesTypeDecorator

# revision identifiers, used by Alembic.
revision: str = 'a2ce75f58c99'
down_revision: Union[str, None] = '9e4aa87bf393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
