"""drop tables

Revision ID: a65bbe3c5b0c
Revises: a0362bfd34e9
Create Date: 2025-04-01 22:09:12.982588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a65bbe3c5b0c'
down_revision: Union[str, None] = 'a0362bfd34e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carbon_footprints')
    op.drop_table('carbon_gasoline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_gasoline',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Тип бензина'),
    sa.Column('octane_number', sa.INTEGER(), autoincrement=False, nullable=False, comment='Октановое число'),
    sa.Column('quality_standard', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Стандарт (Евро-4, Евро-5 и т.п.)'),
    sa.Column('sulfur_content_ppm', sa.INTEGER(), autoincrement=False, nullable=False, comment='Содержание серы (ppm)'),
    sa.Column('aromatic_content_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Доля ароматических углеводородов (%)'),
    sa.Column('co2_per_liter_combustion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Выбросы CO₂ при сгорании (кг/л)'),
    sa.Column('co2_per_liter_production', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Углеродный след производства (кг/л)'),
    sa.Column('total_carbon_footprint', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Общий углеродный след (кг/л)'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Примечание'),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id', name='carbon_gasoline_pkey')
    )
    op.create_table('carbon_footprints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='ID Записи следа'),
    sa.Column('car_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID автомобиля'),
    sa.Column('actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Текущее значение углеродного следа'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name='carbon_footprints_car_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='carbon_footprints_pkey')
    )
    # ### end Alembic commands ###
