"""add details

Revision ID: a76f90739c49
Revises: c5f4c0485014
Create Date: 2025-04-02 14:54:29.040753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76f90739c49'
down_revision: Union[str, None] = 'c5f4c0485014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_user_id_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_user_id_fkey', 'cars', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
