"""change relation from users to profile

Revision ID: b9aafcc670a8
Revises: 4eced21cf74b
Create Date: 2025-04-10 18:50:40.193500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9aafcc670a8'
down_revision: Union[str, None] = '4eced21cf74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tasks', sa.Column('profile_id', sa.UUID(), nullable=False))
    op.drop_constraint('users_tasks_user_id_fkey', 'users_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'users_tasks', 'users_game_profiles', ['profile_id'], ['id'])
    op.drop_column('users_tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tasks', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_tasks', type_='foreignkey')
    op.create_foreign_key('users_tasks_user_id_fkey', 'users_tasks', 'users_game_profiles', ['user_id'], ['id'])
    op.drop_column('users_tasks', 'profile_id')
    # ### end Alembic commands ###
