"""add scores

Revision ID: c5f4c0485014
Revises: a65bbe3c5b0c
Create Date: 2025-04-02 12:37:53.933550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f4c0485014'
down_revision: Union[str, None] = 'a65bbe3c5b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='check_score_range'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cars', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID автомобиля',
               existing_nullable=False)
    op.alter_column('cars', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID владельца',
               existing_nullable=False)
    op.alter_column('cars', 'brand_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Марка',
               existing_nullable=False)
    op.alter_column('cars', 'model_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Модель',
               existing_nullable=False)
    op.alter_column('cars', 'gen_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Модификация',
               existing_nullable=False)
    op.alter_column('cars', 'year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Год выпуска',
               existing_nullable=False)
    op.alter_column('cars', 'mileage',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Пробег',
               existing_nullable=False)
    op.alter_column('cars', 'full',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Полное название',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='TelegramID',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Имя пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               comment='TelegramID',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('cars', 'full',
               existing_type=sa.VARCHAR(),
               comment='Полное название',
               existing_nullable=False)
    op.alter_column('cars', 'mileage',
               existing_type=sa.INTEGER(),
               comment='Пробег',
               existing_nullable=False)
    op.alter_column('cars', 'year',
               existing_type=sa.INTEGER(),
               comment='Год выпуска',
               existing_nullable=False)
    op.alter_column('cars', 'gen_name',
               existing_type=sa.VARCHAR(),
               comment='Модификация',
               existing_nullable=False)
    op.alter_column('cars', 'model_name',
               existing_type=sa.VARCHAR(),
               comment='Модель',
               existing_nullable=False)
    op.alter_column('cars', 'brand_name',
               existing_type=sa.VARCHAR(),
               comment='Марка',
               existing_nullable=False)
    op.alter_column('cars', 'user_id',
               existing_type=sa.UUID(),
               comment='ID владельца',
               existing_nullable=False)
    op.alter_column('cars', 'id',
               existing_type=sa.UUID(),
               comment='ID автомобиля',
               existing_nullable=False)
    op.drop_table('scores')
    # ### end Alembic commands ###
