"""Add new fields cars

Revision ID: cf1a2b61d4ca
Revises: 95e13239bfc9
Create Date: 2025-03-24 10:54:56.208924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1a2b61d4ca'
down_revision: Union[str, None] = '95e13239bfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mileage', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('full', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'full')
    op.drop_column('cars', 'mileage')
    # ### end Alembic commands ###
