"""change game_progress

Revision ID: df3a35224612
Revises: 37909a7ec230
Create Date: 2025-04-03 15:11:23.146529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df3a35224612'
down_revision: Union[str, None] = '37909a7ec230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_progress', sa.Column('car_id', sa.UUID(), nullable=False))
    op.add_column('game_progress', sa.Column('last_wash_car_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'game_progress', 'cars', ['car_id'], ['id'])
    op.drop_column('game_progress', 'first_login_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_progress', sa.Column('first_login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game_progress', type_='foreignkey')
    op.drop_column('game_progress', 'last_wash_car_time')
    op.drop_column('game_progress', 'car_id')
    # ### end Alembic commands ###
